on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    name: Creating Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  publish:
    name: Publishing
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: sudo apt-get install p7zip
      - run: npm install
      - run: npx oclif-dev pack
      - run: npx oclif-dev publish
        env:
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.release.steps.create_release.outputs.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.ref }}/slash-graphql-${{ github.ref }}-darwin-x64.tar.gz
          asset_name: slash-graphql-${{ github.ref }}-darwin-x64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.release.steps.create_release.outputs.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.ref }}/slash-graphql-${{ github.ref }}-linux-arm.tar.gz
          asset_name: slash-graphql-${{ github.ref }}-linux-arm.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.release.steps.create_release.outputs.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.ref }}/slash-graphql-${{ github.ref }}-linux-x64.tar.gz
          asset_name: slash-graphql-${{ github.ref }}-linux-x64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.release.steps.create_release.outputs.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.ref }}/slash-graphql-${{ github.ref }}-win32-x64.tar.gz
          asset_name: slash-graphql-${{ github.ref }}-win32-x64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.release.steps.create_release.outputs.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.ref }}/slash-graphql-${{ github.ref }}-win32-x86.tar.gz
          asset_name: slash-graphql-${{ github.ref }}-win32-x86.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.release.steps.create_release.outputs.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.ref }}/slash-graphql-${{ github.ref }}.tar.gz
          asset_name: slash-graphql-${{ github.ref }}.tar.gz
          asset_content_type: application/gzip
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
