on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Creating Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: v ${{ github.ref }}
          draft: false
          prerelease: false
  build-win:
    runs-on: window-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

  build:
    name: Publishing to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  build:
    name: Creating a oclif binary and uploading to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: oclif-dev pack
      - run: oclif-dev pack:win
      - run: oclif-dev pack:macos
      - run: oclif-dev publish

