name: Build Release Artifacts
on:
  release:
    types: [created, published, released]
jobs:
  publish:
    name: Publish on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: sudo apt-get install p7zip
      - run: npx oclif-dev pack
      - run: npx oclif-dev publish
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.event.release.tag_name }}/slash-graphql-${{ github.event.release.tag_name }}-darwin-x64.tar.gz
          asset_name: slash-graphql-${{ github.event.release.tag_name }}-darwin-x64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.event.release.tag_name }}/slash-graphql-${{ github.event.release.tag_name }}-linux-arm.tar.gz
          asset_name: slash-graphql-${{ github.event.release.tag_name }}-linux-arm.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.event.release.tag_name }}/slash-graphql-${{ github.event.release.tag_name }}-linux-x64.tar.gz
          asset_name: slash-graphql-${{ github.event.release.tag_name }}-linux-x64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.event.release.tag_name }}/slash-graphql-${{ github.event.release.tag_name }}-win32-x64.tar.gz
          asset_name: slash-graphql-${{ github.event.release.tag_name }}-win32-x64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.event.release.tag_name }}/slash-graphql-${{ github.event.release.tag_name }}-win32-x86.tar.gz
          asset_name: slash-graphql-${{ github.event.release.tag_name }}-win32-x86.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/slash-graphql-${{ github.event.release.tag_name }}/slash-graphql-${{ github.event.release.tag_name }}.tar.gz
          asset_name: slash-graphql-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
